name: ${artifactId}
main: ${groupId}.${artifactId}
author: Maxim Varentsov <admin@gtn-craft.ru>
version: ${version}

permissions:
    bogger.use:
        description: Разрешить использование логгера.
        default: true
