name: ${artifactId}
main: ru.gtncraft.bogger.Bogger
author: Maxim Varentsov <admin@gtn-craft.ru>
version: ${version}

permissions:
    bogger.use:
        description: Разрешить использование логгера.
        default: true
