name: bogger
main: ru.gtncraft.bogger.BoggerPlugin
author: Maxim Varentsov <admin@gtn-craft.ru>
version: ${version}

permissions:
    bogger.use:
        description: Allow use bogger plugin
        default: true
